// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRllbTv7pwdYhtueWkSA_mfqPYqSBsDjE',
    appId: '1:995053599025:web:8f6ea74c0f64a440589810',
    messagingSenderId: '995053599025',
    projectId: 'flutter-social-firebase',
    authDomain: 'flutter-social-firebase.firebaseapp.com',
    storageBucket: 'flutter-social-firebase.firebasestorage.app',
    measurementId: 'G-7TDT8R3PKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcKG-tqijTdtH6oRj1g-5Zc15gwqP8M3s',
    appId: '1:995053599025:android:7df76542fb63440b589810',
    messagingSenderId: '995053599025',
    projectId: 'flutter-social-firebase',
    storageBucket: 'flutter-social-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRcFLiKMfyVxMV44-ABoQYZH0MBhKQTFI',
    appId: '1:995053599025:ios:908fa663a1b78291589810',
    messagingSenderId: '995053599025',
    projectId: 'flutter-social-firebase',
    storageBucket: 'flutter-social-firebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterSocialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRcFLiKMfyVxMV44-ABoQYZH0MBhKQTFI',
    appId: '1:995053599025:ios:908fa663a1b78291589810',
    messagingSenderId: '995053599025',
    projectId: 'flutter-social-firebase',
    storageBucket: 'flutter-social-firebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterSocialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRllbTv7pwdYhtueWkSA_mfqPYqSBsDjE',
    appId: '1:995053599025:web:35b06e50a1da504c589810',
    messagingSenderId: '995053599025',
    projectId: 'flutter-social-firebase',
    authDomain: 'flutter-social-firebase.firebaseapp.com',
    storageBucket: 'flutter-social-firebase.firebasestorage.app',
    measurementId: 'G-88VPFCF09N',
  );
}
